[project]
name = "research-os"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arxiv>=2.4.0",
    "langchain-ollama>=1.0.1",
    "langchain[openai]>=1.2.6",
    "python-dotenv>=1.2.1",
    "streamlit>=1.53.0",
    "watchdog>=6.0.0",
]
